### ISSUE TITLE
Feature: Saving Custom Configurations

### ISSUE THREAD

**Issue by StorioGames** [Tony905x/pet-to-npc-transmog#1]
Many thanks for giving the ability to create custom pet configurations. But, I don't think we currently have the ability to save our creations to be able to easily swap between them. This feature would allow you to create a custom configuration, save it to a preset, and be able to swap to that preset easily.

Ideally, we would be able to save as many presets as we like.

**Comment by Tony905x** [comment]
Thanks for feedback, yes I plan on adding this functionality in the future as I agree it would be a lot better

**Comment by StorioGames** [comment]
Thanks Tony!

This plugin has the potential to be widely used! I think it just needs a few small tweaks that I've listed as "issues" and it will be able to do nearly anything anyone would want. Great Plugin!
